// <auto-generated />
namespace EmployeeRegistry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tblWAR_Accomplishments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblWAR_Accomplishments));
        
        string IMigrationMetadata.Id
        {
            get { return "201612172126513_tblWAR_Accomplishments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
